
import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.EN]: {
    title: "Glimmer",
    subtitle: "Document your thoughts.",
    definition: "A thought journal to capture what goes on in your mind and how it affects your feelings.",
    landingDescription: "Whenever a thought strikes you—positive, negative, or intimate—document it here. Track your internal world and find patterns in your thinking.",
    newFeeling: "Log a Thought",
    diary: "Thought Journal",
    save: "Save Thought",
    analyzing: "Analyzing thought...",
    saved: "Saved",
    placeholder: "Elaborate on the context...",
    filterAll: "All",
    filterPositive: "Positive",
    filterNegative: "Negative",
    filterSexual: "Sexual (18+)",
    searchPlaceholder: "Search thoughts, people, context...",
    noEntries: "No thoughts documented yet.",
    back: "Back",
    listening: "Listening...",
    tapToSpeak: "Tap to speak",
    diaryTitle: "Your Mind",
    delete: "Delete",
    insightButton: "Analyze Mindset",
    insightTitle: "AI Reflection",
    copyToClipboard: "Copy Text",
    copied: "Copied!",
    selectSentiment: "How does this thought make you feel?",
    chatPlaceholder: "Type your message...",
    entryComplete: "Thought captured. You can save now.",
    missingInfo: "I need a bit more detail...",
    uploadImage: "Upload Image",
    drawSomething: "Draw",
    drawing: "Drawing Canvas",
    done: "Done",
    cancel: "Cancel",
    clear: "Clear",
    intensity: "Intensity",
    settings: "Settings",
    visibleFeelings: "Thought Categories",
    settingsSubtitle: "Enable or disable tracking for specific types of thoughts.",
    settingsPositive: "Track Positive Thoughts",
    settingsNegative: "Track Negative Thoughts",
    settingsSexual: "Track Sexual Thoughts (18+)",
    settingsSexualSub: "Includes arousal, intimacy, and passion.",
    apiSettingsTitle: "API Configuration",
    apiSettingsSubtitle: "Manage your Google Gemini API Key.",
    apiKeyLabel: "Gemini API Key",
    apiKeyPlaceholder: "Paste your API key here...",
    getApiKey: "Get API Key",
    saveApiKey: "Save Key",
    apiKeySaved: "Key Saved!",
    exportData: "Export JSON",
    shareSummary: "Share Summary",
    shareTitle: "Shareable Thought",
    downloadImage: "Save as Image",
    shareHint: "Generating a card for this thought...",
    selectPersonToShare: "Select Person First",
    statSmile: "You made me smile {count} times since we first met on {date}.",
    managePeople: "Manage People",
    addPerson: "Add Person",
    personName: "Name",
    personAge: "Age",
    personRelation: "Relation",
    personInterests: "Interests (comma separated)",
    personNotes: "Notes / Memories",
    savePersonProfile: "Save Profile",
    updatingProfile: "Updating Profile...",
    noPeople: "No people added yet.",
    filterByPerson: "Filter by Person",
    allPeople: "All People",
    emotions: {
      HAPPY: "Happy",
      EXCITED: "Excited",
      GRATEFUL: "Grateful",
      CALM: "Calm",
      SAD: "Sad",
      ANGRY: "Angry",
      ANXIOUS: "Anxious",
      FRUSTRATED: "Frustrated",
      AROUSED: "Aroused",
      LUSTFUL: "Lustful",
      INTIMATE: "Intimate",
      PASSIONATE: "Passionate"
    },
    // New Form Fields
    thoughtLabel: "What is the thought?",
    reactionLabel: "Reaction (Physical/Emotional)",
    notesLabel: "Context / Details",
    autoFill: "Auto-fill from Context",
    enhance: "Refine Thought",
    chatWithDiary: "Chat with AI",
    chatTitle: "Mind Companion",
    chatInputPlaceholder: "Ask about your thought patterns...",
    chatTemplates: {
      happiness: "What positive thoughts recur?",
      patterns: "Analyze my thinking patterns",
      summary: "Summarize my week",
      people: "Who appears in my thoughts?"
    },
    // V2
    importData: "Import JSON",
    importSuccess: "Data imported successfully!",
    importError: "Invalid file format.",
    edit: "Edit",
    update: "Update Thought",
    calendarView: "Calendar",
    listView: "List",
    compressing: "Compressing Image...",
    // V3
    glimmersDiary: "My Thoughts",
    newEntry: "New Thought",
    previousEntries: "Thought History"
  },
  [Language.SV]: {
    title: "Glimmer",
    subtitle: "Dokumentera dina tankar.",
    definition: "En tankedagbok för att fånga vad som pågår i ditt huvud och hur det påverkar dina känslor.",
    landingDescription: "När en tanke slår dig – positiv, negativ eller intim – dokumentera den här. Spåra din inre värld och hitta mönster i ditt tänkande.",
    newFeeling: "Logga en Tanke",
    diary: "Tankedagbok",
    save: "Spara Tanke",
    analyzing: "Analyserar tanke...",
    saved: "Sparad",
    placeholder: "Utveckla sammanhanget...",
    filterAll: "Alla",
    filterPositive: "Positiva",
    filterNegative: "Negativa",
    filterSexual: "Sexuella (18+)",
    searchPlaceholder: "Sök tankar, personer, kontext...",
    noEntries: "Inga tankar dokumenterade ännu.",
    back: "Tillbaka",
    listening: "Lyssnar...",
    tapToSpeak: "Tryck för att tala",
    diaryTitle: "Ditt Sinne",
    delete: "Radera",
    insightButton: "Analysera Tänkesätt",
    insightTitle: "AI Reflektion",
    copyToClipboard: "Kopiera text",
    copied: "Kopierad!",
    selectSentiment: "Hur får denna tanke dig att känna?",
    chatPlaceholder: "Skriv ditt meddelande...",
    entryComplete: "Tanke fångad. Du kan spara nu.",
    missingInfo: "Jag behöver lite mer detaljer...",
    uploadImage: "Ladda upp bild",
    drawSomething: "Rita",
    drawing: "Rityta",
    done: "Klar",
    cancel: "Avbryt",
    clear: "Rensa",
    intensity: "Intensitet",
    settings: "Inställningar",
    visibleFeelings: "Tankekategorier",
    settingsSubtitle: "Aktivera eller inaktivera spårning för typer av tankar.",
    settingsPositive: "Spåra Positiva Tankar",
    settingsNegative: "Spåra Negativa Tankar",
    settingsSexual: "Spåra Sexuella Tankar (18+)",
    settingsSexualSub: "Inkluderar upphetsning, intimitet och passion.",
    apiSettingsTitle: "API-konfiguration",
    apiSettingsSubtitle: "Hantera din Google Gemini API-nyckel.",
    apiKeyLabel: "Gemini API-nyckel",
    apiKeyPlaceholder: "Klistra in din API-nyckel här...",
    getApiKey: "Hämta API-nyckel",
    saveApiKey: "Spara nyckel",
    apiKeySaved: "Nyckel sparad!",
    exportData: "Exportera JSON",
    shareSummary: "Dela Sammanfattning",
    shareTitle: "Delbar Tanke",
    downloadImage: "Spara som Bild",
    shareHint: "Skapar ett kort för denna tanke...",
    selectPersonToShare: "Välj Person Först",
    statSmile: "Du fick mig att le {count} gånger sedan vi träffades den {date}.",
    managePeople: "Hantera Personer",
    addPerson: "Lägg till Person",
    personName: "Namn",
    personAge: "Ålder",
    personRelation: "Relation",
    personInterests: "Intressen (kommatecken)",
    personNotes: "Anteckningar",
    savePersonProfile: "Spara Profil",
    updatingProfile: "Uppdaterar profil...",
    noPeople: "Inga personer tillagda än.",
    filterByPerson: "Filtrera efter Person",
    allPeople: "Alla Personer",
    emotions: {
      HAPPY: "Glad",
      EXCITED: "Exalterad",
      GRATEFUL: "Tacksam",
      CALM: "Lugn",
      SAD: "Ledsen",
      ANGRY: "Arg",
      ANXIOUS: "Orolig",
      FRUSTRATED: "Frustrerad",
      AROUSED: "Upphetsad",
      LUSTFUL: "Lustfylld",
      INTIMATE: "Intim",
      PASSIONATE: "Passionerad"
    },
    thoughtLabel: "Vad är tanken?",
    reactionLabel: "Reaktion (Fysisk/Emotionell)",
    notesLabel: "Sammanhang / Detaljer",
    autoFill: "Fyll i från kontext",
    enhance: "Förfina Tanke",
    chatWithDiary: "Chatta med AI",
    chatTitle: "Sinneskamrat",
    chatInputPlaceholder: "Fråga om dina tankemönster...",
    chatTemplates: {
      happiness: "Vilka positiva tankar återkommer?",
      patterns: "Analysera mina tankemönster",
      summary: "Sammanfatta veckan",
      people: "Vem dyker upp i mina tankar?"
    },
    importData: "Importera JSON",
    importSuccess: "Data importerades!",
    importError: "Ogiltigt filformat.",
    edit: "Redigera",
    update: "Uppdatera Tanke",
    calendarView: "Kalendar",
    listView: "Lista",
    compressing: "Komprimerar Bild...",
    glimmersDiary: "Mina Tankar",
    newEntry: "Ny Tanke",
    previousEntries: "Tankehistorik"
  },
  [Language.HR]: {
    title: "Glimmer",
    subtitle: "Zabilježite svoje misli.",
    definition: "Dnevnik misli za bilježenje onoga što vam prolazi kroz glavu i kako to utječe na vaše osjećaje.",
    landingDescription: "Kad god vam misao padne na pamet – pozitivna, negativna ili intimna – zabilježite je ovdje. Pratite svoj unutarnji svijet i pronađite obrasce u svom razmišljanju.",
    newFeeling: "Zabilježi Misao",
    diary: "Dnevnik Misli",
    save: "Spremi Misao",
    analyzing: "Analiziram misao...",
    saved: "Spremljeno",
    placeholder: "Objasnite kontekst...",
    filterAll: "Sve",
    filterPositive: "Pozitivno",
    filterNegative: "Negativno",
    filterSexual: "Seksualno (18+)",
    searchPlaceholder: "Pretraži misli, ljude, kontekst...",
    noEntries: "Još nema zabilježenih misli.",
    back: "Natrag",
    listening: "Slušam...",
    tapToSpeak: "Dodirni za govor",
    diaryTitle: "Vaš Um",
    delete: "Izbriši",
    insightButton: "Analiziraj Način Razmišljanja",
    insightTitle: "AI Refleksija",
    copyToClipboard: "Kopiraj tekst",
    copied: "Kopirano!",
    selectSentiment: "Kako se osjećate zbog ove misli?",
    chatPlaceholder: "Upišite svoju poruku...",
    entryComplete: "Misao zabilježena. Možete spremiti.",
    missingInfo: "Trebam još malo detalja...",
    uploadImage: "Učitaj sliku",
    drawSomething: "Nacrtaj",
    drawing: "Platno za crtanje",
    done: "Gotovo",
    cancel: "Odustani",
    clear: "Očisti",
    intensity: "Intenzitet",
    settings: "Postavke",
    visibleFeelings: "Kategorije Misli",
    settingsSubtitle: "Omogućite ili onemogućite praćenje određenih vrsta misli.",
    settingsPositive: "Prati Pozitivne Misli",
    settingsNegative: "Prati Negativne Misli",
    settingsSexual: "Prati Seksualne Misli (18+)",
    settingsSexualSub: "Uključuje uzbuđenje, intimnost i strast.",
    apiSettingsTitle: "API Konfiguracija",
    apiSettingsSubtitle: "Upravljajte svojim Google Gemini API ključem.",
    apiKeyLabel: "Gemini API Ključ",
    apiKeyPlaceholder: "Zalijepite svoj API ključ ovdje...",
    getApiKey: "Dohvati API Ključ",
    saveApiKey: "Spremi Ključ",
    apiKeySaved: "Ključ spremljen!",
    exportData: "Izvezi JSON",
    shareSummary: "Podijeli Sažetak",
    shareTitle: "Misao za Dijeljenje",
    downloadImage: "Spremi kao Sliku",
    shareHint: "Stvaram karticu za ovu misao...",
    selectPersonToShare: "Prvo Odaberite Osobu",
    statSmile: "Nasmijao/la si me {count} puta otkad smo se prvi put sreli {date}.",
    managePeople: "Upravljaj Osobama",
    addPerson: "Dodaj Osobu",
    personName: "Ime",
    personAge: "Dob",
    personRelation: "Odnos",
    personInterests: "Interesi (odvojeni zarezom)",
    personNotes: "Bilješke",
    savePersonProfile: "Spremi Profil",
    updatingProfile: "Ažuriram profil...",
    noPeople: "Još nema dodanih osoba.",
    filterByPerson: "Filtriraj po Osobi",
    allPeople: "Svi Ljudi",
    emotions: {
      HAPPY: "Sretan",
      EXCITED: "Uzbuđen",
      GRATEFUL: "Zahvalan",
      CALM: "Miran",
      SAD: "Tužan",
      ANGRY: "Ljut",
      ANXIOUS: "Anksiozan",
      FRUSTRATED: "Frustriran",
      AROUSED: "Uzbuđen (Sex)",
      LUSTFUL: "Požudan",
      INTIMATE: "Intiman",
      PASSIONATE: "Strastven"
    },
    thoughtLabel: "Koja je misao?",
    reactionLabel: "Reakcija (Fizička/Emocionalna)",
    notesLabel: "Kontekst / Detalji",
    autoFill: "Ispuni iz konteksta",
    enhance: "Poboljšaj Misao",
    chatWithDiary: "Razgovaraj s AI",
    chatTitle: "Mentalni Suputnik",
    chatInputPlaceholder: "Pitaj o svojim obrascima razmišljanja...",
    chatTemplates: {
      happiness: "Koje se pozitivne misli ponavljaju?",
      patterns: "Analiziraj moje obrasce razmišljanja",
      summary: "Sažmi moj tjedan",
      people: "Tko se pojavljuje u mojim mislima?"
    },
    importData: "Uvezi JSON",
    importSuccess: "Podaci uspješno uvezeni!",
    importError: "Neispravan format datoteke.",
    edit: "Uredi",
    update: "Ažuriraj Misao",
    calendarView: "Kalendar",
    listView: "Popis",
    compressing: "Sažimanje Slike...",
    glimmersDiary: "Moje Misli",
    newEntry: "Nova Misao",
    previousEntries: "Povijest Misli"
  }
};